### ISSUE TITLE
[Forge] Dried Spice incompatibility

### ISSUE THREAD

**Issue by CollapitalDev** [Yirmiri/TipsyLib#2]
New versions of TipsyLib (after 1.0.2) appear to be incompatible with most recent Dried Spice. Result is crashing before the game loads fully. This should be listed on the TipsyLib Modrinth page under dependencies/incompatibilities until a compatible version of Dried Spice is released.

**Comment by Yirmiri** [comment]
I am aware of this issue and it will be fixed shorty, currently we start from scratch with Dried Spice to work with multiloader
