### ISSUE TITLE
Hitting entity with thrown egg crashes while ticking entity.

### ISSUE THREAD

**Issue by NyxYoru** [Yirmiri/TipsyLib#4]
Tested on a default flat world with just the mod and fabric api.

Crashes with following error.
"The game crashed whilst ticking entity
Error: java.lang.ClassCastException: class net.minecraft.class_1681 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_1681 and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @69b794e2)"

Log is attached below.
[latest.log](https://github.com/user-attachments/files/16567640/latest.log)

Edit: didnt go back to flat world with just the mod to test this again, but crash appears to happen with arrows as well, changing the arrow damage multiplier attribute additionally does not seem to have any effect on this issue.

**Comment by Yirmiri** [comment]
Thanks for reporting, will release a fix as soon as possible !

**Comment by Yirmiri** [comment]
This is now fixed in an upcoming version (v3.1.1)
