### ISSUE TITLE
Division by Zero crash

### ISSUE THREAD

**Issue by meeprdib** [Yirmiri/TipsyLib#8]
This crash was reported by someone using my Apotheosis addon which uses TipsyLib as a dependency, so I don't have all the details on hand. However, here is what they said as well as the crash log. The conflicting mod in question is [T.O. Tweaks](https://www.curseforge.com/minecraft/mc-mods/to-tweaks-irons-spells) which is closed source at the moment, but they would be more than willing to resolve the issue on their end if needed.

![image](https://github.com/user-attachments/assets/9d659506-8373-4afc-8164-361b4a4dce6a)
![image](https://github.com/user-attachments/assets/1c63ca03-a966-49a4-9ded-28c14eec388b)

[crash-2024-11-29_00.34.49-client.txt](https://github.com/user-attachments/files/17962970/crash-2024-11-29_00.34.49-client.txt)

**Comment by meeprdib** [comment]
Oh, by the way, they were using TipsyLib version 2.0.9 on Minecraft 1.20.1,

**Comment by Yirmiri** [comment]
will look into it thank you !

**Comment by GameTechBC** [comment]
The problem was specifically with a status effect called Sunstrike Effect from T.O Tweaks.. Since my mod is closed source, if you need the code of that particular effect, I can provide you with that no issues... also the necessary details.

**Comment by Yirmiri** [comment]
Sorry for the late reply, been busy with life stuff. It would be very helpful if you could send that over though :) thanks

**Comment by GameTechBC** [comment]
[SunstrikeEffect.zip](https://github.com/user-attachments/files/18023016/SunstrikeEffect.zip)

Sorry I am not very active on github so I didn't checked the reply.. here you go .. the effect.. it is a bit wonky cause I had to use new ResourceLocation thingy since this is a optional dependency stuff so ..can't import directly.. and github doesn't support direct java.. so I zipped the class file.. I should probably remake the code .. cause it's very old ..like when I first started stuff xD

**Comment by Yirmiri** [comment]
Thanks I will work on this sometime tomorrow (hopefully)

**Comment by Yirmiri** [comment]
Unsure if I am missing something but could you provide more information on how the crash occurs? I am unable to recreate the crash on my end.

**Comment by meeprdib** [comment]
The user reporting this has said removing Canary ("performance" mod prone to causing loads of mod conflicts) fixes the issue. This is an issue on neither side, and is not worth looking into to fix.
![Screenshot_20241225-094905_Discord](https://github.com/user-attachments/assets/029fd66b-07c1-4ef9-86b2-69849dcb4c39)
