### ISSUE TITLE
[(Possible) Bug] Effects above a certain level do not display their level correctly

### ISSUE THREAD

**Issue by ZilverLazarus** [Yirmiri/TipsyLib#9]
MC Version: 1.20.1
Platform/Platform Version: NeoForge 47.1.106

In the attached screenshot, you can see that Devour 9 isn't displaying correctly. It might be an Apotheosis Ascended issue since the roman numeral for the effect displays properly when using /effect, but I am going to report it here too just in case.

![TipsyLib Report](https://github.com/user-attachments/assets/c8fa63dd-ad94-4d77-83c5-278459095d15)

**Comment by Yirmiri** [comment]
This is a Minecraft issue (same thing happens with enchantments) and I personally don't have interest in fixing it.
https://bugs.mojang.com/browse/MC-252479

**Comment by meeprdib** [comment]
I'll probably nerf the values given from Ascended to avoid this kind of issue, they were intended to be temporary values anyway, but no-one complained about the balance of them or anything.
